version: '3.7'

services:
    smurf-streamer: &smurf-streamer
        image: "smurf-streamer"
        build: .
        container_name: smurf-streamer
        network_mode: host
        volumes:
            - ${HOME}:${HOME}
            - /data:/data
            - ./fw/current:/tmp/fw/
            - ./scripts:/usr/local/src/smurf-streamer/scripts/
        entrypoint: python3 scripts/start_stream.py
        command: >
            -a 192.168.2.11
            -z /tmp/fw/Kcu105Eth-0x00000101-20190805161102-ruckman-5ecec57-works.zip
        # Debug options
        ####################
        # security_opt:
        #     - seccomp=unconfined
        # cap_add:
        #     - SYS_PTRACE
        # entrypoint: bash
        # command: []
        # stdin_open: true
        # tty: true
        ####################
